import numpy as np

NEUTRONS_PER_RUN = 1000
NUM_RUNS         = 10_000
MAX_COLLISIONS   = 1000
RANDOM_SEED      = 42

SIGMA_S_RANGE = (0.1, 0.9)
SIGMA_A_RANGE = (0.1, 0.6)
SIGMA_F_RANGE = (0.0, 0.4)

SLAB_THICKNESS = 10.0

DATASET_PATH = "neutron_dataset.csv"
RESULTS_DIR  = "results/"

SIGMA_T_MAX = SIGMA_S_RANGE[1] + SIGMA_A_RANGE[1] + SIGMA_F_RANGE[1]
SIGMA_T_MIN = SIGMA_S_RANGE[0] + SIGMA_A_RANGE[0] + SIGMA_F_RANGE[0]